rancher:
    network:
        interfaces:
            eth0:
                address: 192.168.128.100/24
                gateway: 192.168.128.1
                mtu: 1500
                dhcp: false

ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtYp7vtMEuzEnWNePiuxrn/Lm0nmm22mmwDhkAI/WBHKRBJ53CE9cx0S+A4s23MloTWr1zkmf9eU0FAALArxKOZt6rVA6jsNrkMY3HPwfQ2/RpJA2TJZ2fJIsgkhDw4f7a0RDtcDT1tMWfBASlgzKd6umzGA8WTfnm99ep/vNPTACZKJ92txyRYdLnp1bvyCnvfS0/f+S9DSmn97WB5wxNqSfMCWhTf5vdfO7em39kQiilGlo81HE33UYRK37DC5XkaUgjRjrfVYoYkVv116ObzHltTzZ2WlvQ8up5Ewuhbpf9v5EQtA57eGyzgohJ8VLNEAyddwfD1ey/U9nEszAPQ== rsa 2048-072220
